config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  devise_for :users
  resources :lists, except: :index
  resources :cards
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :cards
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        added_attrs = [ :email, :username, :password, :password_confirmation ]
        devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
        devise_parameter_sanitizer.permit :account_update, keys: added_attrs
        devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    
  end

  def new
    @list = List.find(params[:id])
    @card = @list.cards.build
  end

  def create
    list = List.find(params[:card][:list_id])
    @card = list.cards.build(card_params)
    if @card.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      render 'list/index'
    else
      render 'edit'
    end
  end

  def destroy
    
  end

  private
    def card_params
      params.require(:card).permit(:title, :memo)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = current_user.lists
  end

  def new
    @list = current_user.lists.build
  end

  def create
    @list = current_user.lists.build(list_params)
    if @list.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update

  end

  private
    def list_params
      params.require(:list).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/cards/_card.html.erb
<div class="card_item">
    <p><%= card.title %></p>
</div>

app/views/cards/edit.html.erb
<h1>カード編集</h1>
<%= form_with(@card, url: {controller: 'cards', action: 'update'}) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :memo %>
    <%= f.text_field %>
    <%= f.submit '更新' %>
<% end %>

app/views/cards/new.html.erb
<h1>カード作成</h1>
<%= form_for(@card) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :memo %>
    <%= f.text_field :memo %>
    <%= f.hidden_field :list_id, value: @list.id %>
    <%= f.submit '作成' %>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <% if user_signed_in? %>
    <%= link_to current_user.username + "さん", root_path %>
    <%= link_to 'プロフィール変更', edit_user_registration_path %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to 'サインアップ', new_user_registration_path %>
    <%= link_to 'ログイン', new_user_session_path %>
    <% end %>
    <%= link_to 'リストを作成', new_list_path %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kanban</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>    
    <%= yield %>
  </body>
</html>

app/views/lists/_list.html.erb
<div class="list_content">
    <div class="list_title">
        <p><%= list.title %></p>
    </div>
    <div class="cards_index">
        <div class="card_items">
            <%= render partial: 'cards/card', collection: list.cards %>
        </div>
        <button><%= link_to '+ カードを追加', new_card_path(id: list.id) %></button>
    </div>
</div>

app/views/lists/index.html.erb
<div class="lists_index">
    <div class="lists_contents">
        <%= render partial: 'lists/list', collection: @lists %>
    </div>
</div>

app/views/lists/new.html.erb
<h1>List作成</h1>
<%= form_for(@list) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.submit '作成' %>
<% end %>